// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.0
// source: proto/matching.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event สำหรับส่งไป Matching Service
type OrderMatchingRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CarType         string                 `protobuf:"bytes,3,opt,name=car_type,json=carType,proto3" json:"car_type,omitempty"`
	PickupLocation  string                 `protobuf:"bytes,4,opt,name=pickup_location,json=pickupLocation,proto3" json:"pickup_location,omitempty"`
	DropoffLocation string                 `protobuf:"bytes,5,opt,name=dropoff_location,json=dropoffLocation,proto3" json:"dropoff_location,omitempty"`
	FinalTotal      float64                `protobuf:"fixed64,6,opt,name=final_total,json=finalTotal,proto3" json:"final_total,omitempty"`
	CouponCode      string                 `protobuf:"bytes,7,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	Distance        float64                `protobuf:"fixed64,8,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration        float64                `protobuf:"fixed64,9,opt,name=duration,proto3" json:"duration,omitempty"`
	PickupPolyline  string                 `protobuf:"bytes,10,opt,name=pickup_polyline,json=pickupPolyline,proto3" json:"pickup_polyline,omitempty"`
	DropoffPolyline string                 `protobuf:"bytes,11,opt,name=dropoff_polyline,json=dropoffPolyline,proto3" json:"dropoff_polyline,omitempty"`
	Timestamp       int64                  `protobuf:"varint,12,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderMatchingRequest) Reset() {
	*x = OrderMatchingRequest{}
	mi := &file_proto_matching_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderMatchingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderMatchingRequest) ProtoMessage() {}

func (x *OrderMatchingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_matching_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderMatchingRequest.ProtoReflect.Descriptor instead.
func (*OrderMatchingRequest) Descriptor() ([]byte, []int) {
	return file_proto_matching_proto_rawDescGZIP(), []int{0}
}

func (x *OrderMatchingRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderMatchingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderMatchingRequest) GetCarType() string {
	if x != nil {
		return x.CarType
	}
	return ""
}

func (x *OrderMatchingRequest) GetPickupLocation() string {
	if x != nil {
		return x.PickupLocation
	}
	return ""
}

func (x *OrderMatchingRequest) GetDropoffLocation() string {
	if x != nil {
		return x.DropoffLocation
	}
	return ""
}

func (x *OrderMatchingRequest) GetFinalTotal() float64 {
	if x != nil {
		return x.FinalTotal
	}
	return 0
}

func (x *OrderMatchingRequest) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

func (x *OrderMatchingRequest) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *OrderMatchingRequest) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *OrderMatchingRequest) GetPickupPolyline() string {
	if x != nil {
		return x.PickupPolyline
	}
	return ""
}

func (x *OrderMatchingRequest) GetDropoffPolyline() string {
	if x != nil {
		return x.DropoffPolyline
	}
	return ""
}

func (x *OrderMatchingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_matching_proto protoreflect.FileDescriptor

const file_proto_matching_proto_rawDesc = "" +
	"\n" +
	"\x14proto/matching.proto\x12\x02pb\"\xa5\x03\n" +
	"\x14OrderMatchingRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bcar_type\x18\x03 \x01(\tR\acarType\x12'\n" +
	"\x0fpickup_location\x18\x04 \x01(\tR\x0epickupLocation\x12)\n" +
	"\x10dropoff_location\x18\x05 \x01(\tR\x0fdropoffLocation\x12\x1f\n" +
	"\vfinal_total\x18\x06 \x01(\x01R\n" +
	"finalTotal\x12\x1f\n" +
	"\vcoupon_code\x18\a \x01(\tR\n" +
	"couponCode\x12\x1a\n" +
	"\bdistance\x18\b \x01(\x01R\bdistance\x12\x1a\n" +
	"\bduration\x18\t \x01(\x01R\bduration\x12'\n" +
	"\x0fpickup_polyline\x18\n" +
	" \x01(\tR\x0epickupPolyline\x12)\n" +
	"\x10dropoff_polyline\x18\v \x01(\tR\x0fdropoffPolyline\x12\x1c\n" +
	"\ttimestamp\x18\f \x01(\x03R\ttimestampB+Z)dift_backend_go/order-service/proto/pb;pbb\x06proto3"

var (
	file_proto_matching_proto_rawDescOnce sync.Once
	file_proto_matching_proto_rawDescData []byte
)

func file_proto_matching_proto_rawDescGZIP() []byte {
	file_proto_matching_proto_rawDescOnce.Do(func() {
		file_proto_matching_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_matching_proto_rawDesc), len(file_proto_matching_proto_rawDesc)))
	})
	return file_proto_matching_proto_rawDescData
}

var file_proto_matching_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_matching_proto_goTypes = []any{
	(*OrderMatchingRequest)(nil), // 0: pb.OrderMatchingRequest
}
var file_proto_matching_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_matching_proto_init() }
func file_proto_matching_proto_init() {
	if File_proto_matching_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_matching_proto_rawDesc), len(file_proto_matching_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_matching_proto_goTypes,
		DependencyIndexes: file_proto_matching_proto_depIdxs,
		MessageInfos:      file_proto_matching_proto_msgTypes,
	}.Build()
	File_proto_matching_proto = out.File
	file_proto_matching_proto_goTypes = nil
	file_proto_matching_proto_depIdxs = nil
}
