// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.0
// source: proto/order_cancel.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ส่งไป Driver Service
type PassengerCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassengerCancelRequest) Reset() {
	*x = PassengerCancelRequest{}
	mi := &file_proto_order_cancel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassengerCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassengerCancelRequest) ProtoMessage() {}

func (x *PassengerCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_cancel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassengerCancelRequest.ProtoReflect.Descriptor instead.
func (*PassengerCancelRequest) Descriptor() ([]byte, []int) {
	return file_proto_order_cancel_proto_rawDescGZIP(), []int{0}
}

func (x *PassengerCancelRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PassengerCancelRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PassengerCancelRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// รับจาก Driver Service
type DriverCancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // cancelled / failed
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverCancelResponse) Reset() {
	*x = DriverCancelResponse{}
	mi := &file_proto_order_cancel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverCancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverCancelResponse) ProtoMessage() {}

func (x *DriverCancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_order_cancel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverCancelResponse.ProtoReflect.Descriptor instead.
func (*DriverCancelResponse) Descriptor() ([]byte, []int) {
	return file_proto_order_cancel_proto_rawDescGZIP(), []int{1}
}

func (x *DriverCancelResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DriverCancelResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *DriverCancelResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DriverCancelResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_order_cancel_proto protoreflect.FileDescriptor

const file_proto_order_cancel_proto_rawDesc = "" +
	"\n" +
	"\x18proto/order_cancel.proto\x12\x02pb\"j\n" +
	"\x16PassengerCancelRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\x84\x01\n" +
	"\x14DriverCancelResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestampB+Z)dift_backend_go/order-service/proto/pb;pbb\x06proto3"

var (
	file_proto_order_cancel_proto_rawDescOnce sync.Once
	file_proto_order_cancel_proto_rawDescData []byte
)

func file_proto_order_cancel_proto_rawDescGZIP() []byte {
	file_proto_order_cancel_proto_rawDescOnce.Do(func() {
		file_proto_order_cancel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_order_cancel_proto_rawDesc), len(file_proto_order_cancel_proto_rawDesc)))
	})
	return file_proto_order_cancel_proto_rawDescData
}

var file_proto_order_cancel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_order_cancel_proto_goTypes = []any{
	(*PassengerCancelRequest)(nil), // 0: pb.PassengerCancelRequest
	(*DriverCancelResponse)(nil),   // 1: pb.DriverCancelResponse
}
var file_proto_order_cancel_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_order_cancel_proto_init() }
func file_proto_order_cancel_proto_init() {
	if File_proto_order_cancel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_order_cancel_proto_rawDesc), len(file_proto_order_cancel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_order_cancel_proto_goTypes,
		DependencyIndexes: file_proto_order_cancel_proto_depIdxs,
		MessageInfos:      file_proto_order_cancel_proto_msgTypes,
	}.Build()
	File_proto_order_cancel_proto = out.File
	file_proto_order_cancel_proto_goTypes = nil
	file_proto_order_cancel_proto_depIdxs = nil
}
