// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.0
// source: proto/travel.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TravelLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float64                `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng           float64                `protobuf:"fixed64,2,opt,name=lng,proto3" json:"lng,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TravelLocation) Reset() {
	*x = TravelLocation{}
	mi := &file_proto_travel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TravelLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TravelLocation) ProtoMessage() {}

func (x *TravelLocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TravelLocation.ProtoReflect.Descriptor instead.
func (*TravelLocation) Descriptor() ([]byte, []int) {
	return file_proto_travel_proto_rawDescGZIP(), []int{0}
}

func (x *TravelLocation) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *TravelLocation) GetLng() float64 {
	if x != nil {
		return x.Lng
	}
	return 0
}

func (x *TravelLocation) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type TravelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteId       string                 `protobuf:"bytes,1,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Pickup        *TravelLocation        `protobuf:"bytes,3,opt,name=pickup,proto3" json:"pickup,omitempty"`
	Dropoff       *TravelLocation        `protobuf:"bytes,4,opt,name=dropoff,proto3" json:"dropoff,omitempty"`
	CarType       string                 `protobuf:"bytes,5,opt,name=car_type,json=carType,proto3" json:"car_type,omitempty"`
	Distance      float64                `protobuf:"fixed64,6,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration      float64                `protobuf:"fixed64,7,opt,name=duration,proto3" json:"duration,omitempty"`
	Price         float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	Timestamp     int64                  `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TravelRequest) Reset() {
	*x = TravelRequest{}
	mi := &file_proto_travel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TravelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TravelRequest) ProtoMessage() {}

func (x *TravelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_travel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TravelRequest.ProtoReflect.Descriptor instead.
func (*TravelRequest) Descriptor() ([]byte, []int) {
	return file_proto_travel_proto_rawDescGZIP(), []int{1}
}

func (x *TravelRequest) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *TravelRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TravelRequest) GetPickup() *TravelLocation {
	if x != nil {
		return x.Pickup
	}
	return nil
}

func (x *TravelRequest) GetDropoff() *TravelLocation {
	if x != nil {
		return x.Dropoff
	}
	return nil
}

func (x *TravelRequest) GetCarType() string {
	if x != nil {
		return x.CarType
	}
	return ""
}

func (x *TravelRequest) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *TravelRequest) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TravelRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TravelRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TravelRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_travel_proto protoreflect.FileDescriptor

const file_proto_travel_proto_rawDesc = "" +
	"\n" +
	"\x12proto/travel.proto\x12\x02pb\"N\n" +
	"\x0eTravelLocation\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lng\x18\x02 \x01(\x01R\x03lng\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"\xc0\x02\n" +
	"\rTravelRequest\x12\x19\n" +
	"\broute_id\x18\x01 \x01(\tR\arouteId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12*\n" +
	"\x06pickup\x18\x03 \x01(\v2\x12.pb.TravelLocationR\x06pickup\x12,\n" +
	"\adropoff\x18\x04 \x01(\v2\x12.pb.TravelLocationR\adropoff\x12\x19\n" +
	"\bcar_type\x18\x05 \x01(\tR\acarType\x12\x1a\n" +
	"\bdistance\x18\x06 \x01(\x01R\bdistance\x12\x1a\n" +
	"\bduration\x18\a \x01(\x01R\bduration\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x03R\ttimestampB+Z)dift_backend_go/order-service/proto/pb;pbb\x06proto3"

var (
	file_proto_travel_proto_rawDescOnce sync.Once
	file_proto_travel_proto_rawDescData []byte
)

func file_proto_travel_proto_rawDescGZIP() []byte {
	file_proto_travel_proto_rawDescOnce.Do(func() {
		file_proto_travel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_travel_proto_rawDesc), len(file_proto_travel_proto_rawDesc)))
	})
	return file_proto_travel_proto_rawDescData
}

var file_proto_travel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_travel_proto_goTypes = []any{
	(*TravelLocation)(nil), // 0: pb.TravelLocation
	(*TravelRequest)(nil),  // 1: pb.TravelRequest
}
var file_proto_travel_proto_depIdxs = []int32{
	0, // 0: pb.TravelRequest.pickup:type_name -> pb.TravelLocation
	0, // 1: pb.TravelRequest.dropoff:type_name -> pb.TravelLocation
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_travel_proto_init() }
func file_proto_travel_proto_init() {
	if File_proto_travel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_travel_proto_rawDesc), len(file_proto_travel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_travel_proto_goTypes,
		DependencyIndexes: file_proto_travel_proto_depIdxs,
		MessageInfos:      file_proto_travel_proto_msgTypes,
	}.Build()
	File_proto_travel_proto = out.File
	file_proto_travel_proto_goTypes = nil
	file_proto_travel_proto_depIdxs = nil
}
