// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.0
// source: proto/trip_history.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TripHistoryEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	DriverId        string                 `protobuf:"bytes,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	DriverName      string                 `protobuf:"bytes,5,opt,name=driver_name,json=driverName,proto3" json:"driver_name,omitempty"`
	DriverCarModel  string                 `protobuf:"bytes,6,opt,name=driver_car_model,json=driverCarModel,proto3" json:"driver_car_model,omitempty"`
	DriverAvatarUrl string                 `protobuf:"bytes,7,opt,name=driver_avatar_url,json=driverAvatarUrl,proto3" json:"driver_avatar_url,omitempty"`
	CarPlate        string                 `protobuf:"bytes,8,opt,name=car_plate,json=carPlate,proto3" json:"car_plate,omitempty"`
	CarType         string                 `protobuf:"bytes,9,opt,name=car_type,json=carType,proto3" json:"car_type,omitempty"`
	PickupLocation  string                 `protobuf:"bytes,10,opt,name=pickup_location,json=pickupLocation,proto3" json:"pickup_location,omitempty"`
	DropoffLocation string                 `protobuf:"bytes,11,opt,name=dropoff_location,json=dropoffLocation,proto3" json:"dropoff_location,omitempty"`
	Distance        float64                `protobuf:"fixed64,12,opt,name=distance,proto3" json:"distance,omitempty"`
	Duration        float64                `protobuf:"fixed64,13,opt,name=duration,proto3" json:"duration,omitempty"`
	PickupPolyline  string                 `protobuf:"bytes,14,opt,name=pickup_polyline,json=pickupPolyline,proto3" json:"pickup_polyline,omitempty"`
	DropoffPolyline string                 `protobuf:"bytes,15,opt,name=dropoff_polyline,json=dropoffPolyline,proto3" json:"dropoff_polyline,omitempty"`
	FinalTotal      float64                `protobuf:"fixed64,16,opt,name=final_total,json=finalTotal,proto3" json:"final_total,omitempty"`
	CouponCode      string                 `protobuf:"bytes,17,opt,name=coupon_code,json=couponCode,proto3" json:"coupon_code,omitempty"`
	Timestamp       int64                  `protobuf:"varint,18,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,19,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TripHistoryEvent) Reset() {
	*x = TripHistoryEvent{}
	mi := &file_proto_trip_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripHistoryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripHistoryEvent) ProtoMessage() {}

func (x *TripHistoryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripHistoryEvent.ProtoReflect.Descriptor instead.
func (*TripHistoryEvent) Descriptor() ([]byte, []int) {
	return file_proto_trip_history_proto_rawDescGZIP(), []int{0}
}

func (x *TripHistoryEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *TripHistoryEvent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TripHistoryEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TripHistoryEvent) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *TripHistoryEvent) GetDriverName() string {
	if x != nil {
		return x.DriverName
	}
	return ""
}

func (x *TripHistoryEvent) GetDriverCarModel() string {
	if x != nil {
		return x.DriverCarModel
	}
	return ""
}

func (x *TripHistoryEvent) GetDriverAvatarUrl() string {
	if x != nil {
		return x.DriverAvatarUrl
	}
	return ""
}

func (x *TripHistoryEvent) GetCarPlate() string {
	if x != nil {
		return x.CarPlate
	}
	return ""
}

func (x *TripHistoryEvent) GetCarType() string {
	if x != nil {
		return x.CarType
	}
	return ""
}

func (x *TripHistoryEvent) GetPickupLocation() string {
	if x != nil {
		return x.PickupLocation
	}
	return ""
}

func (x *TripHistoryEvent) GetDropoffLocation() string {
	if x != nil {
		return x.DropoffLocation
	}
	return ""
}

func (x *TripHistoryEvent) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *TripHistoryEvent) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TripHistoryEvent) GetPickupPolyline() string {
	if x != nil {
		return x.PickupPolyline
	}
	return ""
}

func (x *TripHistoryEvent) GetDropoffPolyline() string {
	if x != nil {
		return x.DropoffPolyline
	}
	return ""
}

func (x *TripHistoryEvent) GetFinalTotal() float64 {
	if x != nil {
		return x.FinalTotal
	}
	return 0
}

func (x *TripHistoryEvent) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

func (x *TripHistoryEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TripHistoryEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_proto_trip_history_proto protoreflect.FileDescriptor

const file_proto_trip_history_proto_rawDesc = "" +
	"\n" +
	"\x18proto/trip_history.proto\x12\x02pb\"\xe7\x05\n" +
	"\x10TripHistoryEvent\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\tR\bdriverId\x12\x1f\n" +
	"\vdriver_name\x18\x05 \x01(\tR\n" +
	"driverName\x12(\n" +
	"\x10driver_car_model\x18\x06 \x01(\tR\x0edriverCarModel\x12*\n" +
	"\x11driver_avatar_url\x18\a \x01(\tR\x0fdriverAvatarUrl\x12\x1b\n" +
	"\tcar_plate\x18\b \x01(\tR\bcarPlate\x12\x19\n" +
	"\bcar_type\x18\t \x01(\tR\acarType\x12'\n" +
	"\x0fpickup_location\x18\n" +
	" \x01(\tR\x0epickupLocation\x12)\n" +
	"\x10dropoff_location\x18\v \x01(\tR\x0fdropoffLocation\x12\x1a\n" +
	"\bdistance\x18\f \x01(\x01R\bdistance\x12\x1a\n" +
	"\bduration\x18\r \x01(\x01R\bduration\x12'\n" +
	"\x0fpickup_polyline\x18\x0e \x01(\tR\x0epickupPolyline\x12)\n" +
	"\x10dropoff_polyline\x18\x0f \x01(\tR\x0fdropoffPolyline\x12\x1f\n" +
	"\vfinal_total\x18\x10 \x01(\x01R\n" +
	"finalTotal\x12\x1f\n" +
	"\vcoupon_code\x18\x11 \x01(\tR\n" +
	"couponCode\x12\x1c\n" +
	"\ttimestamp\x18\x12 \x01(\x03R\ttimestamp\x12>\n" +
	"\bmetadata\x18\x13 \x03(\v2\".pb.TripHistoryEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B+Z)dift_backend_go/order-service/proto/pb;pbb\x06proto3"

var (
	file_proto_trip_history_proto_rawDescOnce sync.Once
	file_proto_trip_history_proto_rawDescData []byte
)

func file_proto_trip_history_proto_rawDescGZIP() []byte {
	file_proto_trip_history_proto_rawDescOnce.Do(func() {
		file_proto_trip_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_trip_history_proto_rawDesc), len(file_proto_trip_history_proto_rawDesc)))
	})
	return file_proto_trip_history_proto_rawDescData
}

var file_proto_trip_history_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_trip_history_proto_goTypes = []any{
	(*TripHistoryEvent)(nil), // 0: pb.TripHistoryEvent
	nil,                      // 1: pb.TripHistoryEvent.MetadataEntry
}
var file_proto_trip_history_proto_depIdxs = []int32{
	1, // 0: pb.TripHistoryEvent.metadata:type_name -> pb.TripHistoryEvent.MetadataEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_trip_history_proto_init() }
func file_proto_trip_history_proto_init() {
	if File_proto_trip_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_trip_history_proto_rawDesc), len(file_proto_trip_history_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_trip_history_proto_goTypes,
		DependencyIndexes: file_proto_trip_history_proto_depIdxs,
		MessageInfos:      file_proto_trip_history_proto_msgTypes,
	}.Build()
	File_proto_trip_history_proto = out.File
	file_proto_trip_history_proto_goTypes = nil
	file_proto_trip_history_proto_depIdxs = nil
}
