// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.0
// source: proto/usercoupon.proto

package pb_usercoupon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListUserCouponsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserCouponsRequest) Reset() {
	*x = ListUserCouponsRequest{}
	mi := &file_proto_usercoupon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserCouponsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserCouponsRequest) ProtoMessage() {}

func (x *ListUserCouponsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usercoupon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserCouponsRequest.ProtoReflect.Descriptor instead.
func (*ListUserCouponsRequest) Descriptor() ([]byte, []int) {
	return file_proto_usercoupon_proto_rawDescGZIP(), []int{0}
}

func (x *ListUserCouponsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListUserCouponsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coupons       []*UserCoupon          `protobuf:"bytes,1,rep,name=coupons,proto3" json:"coupons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserCouponsResponse) Reset() {
	*x = ListUserCouponsResponse{}
	mi := &file_proto_usercoupon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserCouponsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserCouponsResponse) ProtoMessage() {}

func (x *ListUserCouponsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usercoupon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserCouponsResponse.ProtoReflect.Descriptor instead.
func (*ListUserCouponsResponse) Descriptor() ([]byte, []int) {
	return file_proto_usercoupon_proto_rawDescGZIP(), []int{1}
}

func (x *ListUserCouponsResponse) GetCoupons() []*UserCoupon {
	if x != nil {
		return x.Coupons
	}
	return nil
}

type UserCoupon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Discount      float64                `protobuf:"fixed64,4,opt,name=discount,proto3" json:"discount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	ValidUntil    int64                  `protobuf:"varint,6,opt,name=valid_until,json=validUntil,proto3" json:"valid_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCoupon) Reset() {
	*x = UserCoupon{}
	mi := &file_proto_usercoupon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCoupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCoupon) ProtoMessage() {}

func (x *UserCoupon) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usercoupon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCoupon.ProtoReflect.Descriptor instead.
func (*UserCoupon) Descriptor() ([]byte, []int) {
	return file_proto_usercoupon_proto_rawDescGZIP(), []int{2}
}

func (x *UserCoupon) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UserCoupon) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UserCoupon) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UserCoupon) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *UserCoupon) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UserCoupon) GetValidUntil() int64 {
	if x != nil {
		return x.ValidUntil
	}
	return 0
}

var File_proto_usercoupon_proto protoreflect.FileDescriptor

const file_proto_usercoupon_proto_rawDesc = "" +
	"\n" +
	"\x16proto/usercoupon.proto\x12\rpb_usercoupon\"1\n" +
	"\x16ListUserCouponsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"N\n" +
	"\x17ListUserCouponsResponse\x123\n" +
	"\acoupons\x18\x01 \x03(\v2\x19.pb_usercoupon.UserCouponR\acoupons\"\xb1\x01\n" +
	"\n" +
	"UserCoupon\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bdiscount\x18\x04 \x01(\x01R\bdiscount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1f\n" +
	"\vvalid_until\x18\x06 \x01(\x03R\n" +
	"validUntil2u\n" +
	"\x11UserCouponService\x12`\n" +
	"\x0fListUserCoupons\x12%.pb_usercoupon.ListUserCouponsRequest\x1a&.pb_usercoupon.ListUserCouponsResponseBAZ?dift_backend_go/order-service/proto/pb/usercoupon;pb_usercouponb\x06proto3"

var (
	file_proto_usercoupon_proto_rawDescOnce sync.Once
	file_proto_usercoupon_proto_rawDescData []byte
)

func file_proto_usercoupon_proto_rawDescGZIP() []byte {
	file_proto_usercoupon_proto_rawDescOnce.Do(func() {
		file_proto_usercoupon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_usercoupon_proto_rawDesc), len(file_proto_usercoupon_proto_rawDesc)))
	})
	return file_proto_usercoupon_proto_rawDescData
}

var file_proto_usercoupon_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_usercoupon_proto_goTypes = []any{
	(*ListUserCouponsRequest)(nil),  // 0: pb_usercoupon.ListUserCouponsRequest
	(*ListUserCouponsResponse)(nil), // 1: pb_usercoupon.ListUserCouponsResponse
	(*UserCoupon)(nil),              // 2: pb_usercoupon.UserCoupon
}
var file_proto_usercoupon_proto_depIdxs = []int32{
	2, // 0: pb_usercoupon.ListUserCouponsResponse.coupons:type_name -> pb_usercoupon.UserCoupon
	0, // 1: pb_usercoupon.UserCouponService.ListUserCoupons:input_type -> pb_usercoupon.ListUserCouponsRequest
	1, // 2: pb_usercoupon.UserCouponService.ListUserCoupons:output_type -> pb_usercoupon.ListUserCouponsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_usercoupon_proto_init() }
func file_proto_usercoupon_proto_init() {
	if File_proto_usercoupon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_usercoupon_proto_rawDesc), len(file_proto_usercoupon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_usercoupon_proto_goTypes,
		DependencyIndexes: file_proto_usercoupon_proto_depIdxs,
		MessageInfos:      file_proto_usercoupon_proto_msgTypes,
	}.Build()
	File_proto_usercoupon_proto = out.File
	file_proto_usercoupon_proto_goTypes = nil
	file_proto_usercoupon_proto_depIdxs = nil
}
