// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.0
// source: proto/usercoupon.proto

package pb_usercoupon

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserCouponService_ListUserCoupons_FullMethodName = "/pb_usercoupon.UserCouponService/ListUserCoupons"
)

// UserCouponServiceClient is the client API for UserCouponService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserCouponServiceClient interface {
	ListUserCoupons(ctx context.Context, in *ListUserCouponsRequest, opts ...grpc.CallOption) (*ListUserCouponsResponse, error)
}

type userCouponServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserCouponServiceClient(cc grpc.ClientConnInterface) UserCouponServiceClient {
	return &userCouponServiceClient{cc}
}

func (c *userCouponServiceClient) ListUserCoupons(ctx context.Context, in *ListUserCouponsRequest, opts ...grpc.CallOption) (*ListUserCouponsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserCouponsResponse)
	err := c.cc.Invoke(ctx, UserCouponService_ListUserCoupons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserCouponServiceServer is the server API for UserCouponService service.
// All implementations must embed UnimplementedUserCouponServiceServer
// for forward compatibility.
type UserCouponServiceServer interface {
	ListUserCoupons(context.Context, *ListUserCouponsRequest) (*ListUserCouponsResponse, error)
	mustEmbedUnimplementedUserCouponServiceServer()
}

// UnimplementedUserCouponServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserCouponServiceServer struct{}

func (UnimplementedUserCouponServiceServer) ListUserCoupons(context.Context, *ListUserCouponsRequest) (*ListUserCouponsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserCoupons not implemented")
}
func (UnimplementedUserCouponServiceServer) mustEmbedUnimplementedUserCouponServiceServer() {}
func (UnimplementedUserCouponServiceServer) testEmbeddedByValue()                           {}

// UnsafeUserCouponServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserCouponServiceServer will
// result in compilation errors.
type UnsafeUserCouponServiceServer interface {
	mustEmbedUnimplementedUserCouponServiceServer()
}

func RegisterUserCouponServiceServer(s grpc.ServiceRegistrar, srv UserCouponServiceServer) {
	// If the following call panics, it indicates UnimplementedUserCouponServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserCouponService_ServiceDesc, srv)
}

func _UserCouponService_ListUserCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserCouponsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserCouponServiceServer).ListUserCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserCouponService_ListUserCoupons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserCouponServiceServer).ListUserCoupons(ctx, req.(*ListUserCouponsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserCouponService_ServiceDesc is the grpc.ServiceDesc for UserCouponService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserCouponService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb_usercoupon.UserCouponService",
	HandlerType: (*UserCouponServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUserCoupons",
			Handler:    _UserCouponService_ListUserCoupons_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/usercoupon.proto",
}
